
name: GitHub Actions Demo

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    


    steps:
      - name: chevout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: list files
        run: |
          ls ${{ github.workspace }}

      - name: esp-idf build
      
        uses: espressif/esp-idf-ci-action@v1
        with: 
          command: cd ${{ github.workspace }} && ls && esp-idf build


