
name: GitHub Actions Demo

on: [push]

jobs:
  build:
  
    runs-on: ubuntu-latest
    


    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          
      - name: go to folder  
        run: cd ${{ github.workspace }} && ls

      - name: esp-idf build
        uses: espressif/esp-idf-ci-action@v1
        with: 
          command: ${{ github.workspace }}/idf.py build


